# Base configs
baseurl: "https://tommy-nguyen17.github.io/Pokemon-Standard-Playables/"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
image_rotating_thumbs_loc: "/rotating_images/rotating_thumbs"
image_rotating_fulls_loc: "/rotating_images/rotating_fulls"
google_analytics: "UA-46465113-2"
defaults: 
  - scope: 
      path: "images/fulls"
    values: 
      non_rotating_image: true
  - scope: 
      path: "rotating_images/rotating_fulls"
    values: 
      rotating_image: true
# UI configs
title: "Pokemon Standard Playables"
subtitle: "Everything that's meta relevant for the 2026-2027 Pokemon TCG Standard Format"
author: "Tommy Nguyen"
header:
 title: "Pokemon Standard Playables"
 subtitle: "by Tommy Nguyen"
footer:
 name: "Hey there, my name is Tommy!"
 bio: "I am a software and game developer. I love playing PTCG and software development. I hope this website serves the community and helps players with rotation!"
 memory: "In memory of JustInBasil. Thank you for everything."